ALTER PROCEDURE [dbo].[sp_FillObjMegnev2]
	@pObjTip varchar(2),
	@pAKTIV integer = 1,
	@pMEGNEV VARCHAR(50) = NULL,
	@ELSOOSZLOP varchar(1) = NULL
AS
SET NOCOUNT ONDECLARE @IS_AKTIV VARCHAR(1)IF @pAKTIV = 1BEGIN	SELECT @IS_AKTIV = 'n'ENDELSEBEGIN	SELECT @IS_AKTIV = 'y'ENDSET NOCOUNT OFF
IF @pObjTip = '01'	--EpuletBEGIN	SELECT		OBJEKTUM.ID,		RTRIM(COALESCE(UTCA, ' - ')),		RTRIM(COALESCE(HSZ, ' - ')),		COALESCE(EPULSZ, ' - '),		' '	FROM		OBJEKTUM JOIN EPULET ON EPULET.ID = OBJEKTUM.ID	WHERE		OBJTIP = '01' AND (AKTIV='y' OR AKTIV = @IS_AKTIV)		AND (OBJEKTUM.MEGNEV LIKE coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))	ORDER BY		UTCA,		HSZ,		EPULSZENDELSE IF @pObjTip = '37'	--LepcsohazBEGIN	SELECT		ID,		RTRIM(COALESCE(CIM, ' - ')),		' ',		' ',		' '	FROM		LEPCSOHAZ	ORDER BY		CIMENDELSE	--Ha nem lepcsohaz es nem epuletBEGIN	IF @ELSOOSZLOP = 'T'	BEGIN		SELECT			ID,			COALESCE(TELEPHSZ, ' - '),			COALESCE(MEGNEV, ' - '),			COALESCE(TIPUS, ' - '),			COALESCE(GYSZAM, ' - ')		FROM			OBJEKTUM		WHERE			OBJTIP=@pObjTip AND (AKTIV='y' OR AKTIV = @IS_AKTIV)			AND (OBJEKTUM.MEGNEV LIKE coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))		ORDER BY			TELEPHSZ,					MEGNEV,			TIPUS	END
	ELSE	BEGIN		SELECT			ID,			COALESCE(MEGNEV, ' - '),			COALESCE(TIPUS, ' - '),			COALESCE(TELEPHSZ, ' - '),			COALESCE(GYSZAM, ' - ')		FROM			OBJEKTUM		WHERE			OBJTIP=@pObjTip AND (AKTIV='y' OR AKTIV = @IS_AKTIV)			AND (OBJEKTUM.MEGNEV LIKE coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))		ORDER BY			MEGNEV,			TIPUS,			TELEPHSZ	ENDEND
RETURN 0