ALTER PROCEDURE [dbo].[sp_LekerdAlt]
@pOBJTIP VARCHAR(2),
@pID INTEGER=NULL,
@HOTELJTOL REAL=NULL,
@HOTELJIG REAL=NULL,
@NEVLTELJTOL REAL=NULL,
@NEVLTELJIG REAL=NULL,
@GAZCSUCSTOL REAL=NULL,
@GAZCSUCSIG REAL=NULL,
@VILLCSUCSNYTOL REAL=NULL,
@VILLCSUCSNYIG REAL=NULL,
@VILLCSUCSTTOL REAL=NULL,
@VILLCSUCSTIG REAL=NULL,
@TERFARAMTOL REAL=NULL,
@TERFARAMIG REAL=NULL,
@HOMERSTOL REAL=NULL,
@HOMERSIG REAL=NULL,
@PRIM_ARAMTOL REAL=NULL,
@PRIM_ARAMIG REAL=NULL,
@SZEKU_TOMTOL REAL=NULL,
@SZEKU_TOMIG REAL=NULL,
@VIZATMEROTOL REAL=NULL,
@VIZATMEROIG REAL=NULL,
@VIZIMPULZUSTOL REAL=NULL,
@VIZIMPULZUSIG REAL=NULL,
@ERZVEZTOL REAL=NULL,
@ERZVEZIG REAL=NULL,
@ERZBENYTOL REAL=NULL,
@ERZBENYIG REAL=NULL,
@HOOSZIMPTOL REAL=NULL,
@HOOSZIMPIG REAL=NULL,
@329 VARCHAR(2)=NULL,
@278 VARCHAR(3)=NULL,
@277 VARCHAR(3)=NULL,
@281 VARCHAR(3)=NULL,
@274 VARCHAR(3)=NULL,@pMEGNEV VARCHAR(50)=NULL
AS

IF @pOBJTIP	= '01'
BEGIN
	SELECT
		OBJEKTUM.ID,
		MEGNEV,
		Q289.KODENEV AS	VAROS,
		UTCA,
		HSZ,
		--AZON,
		IRSZAM,
		Q274.KODENEV AS	EPULTIP,
		HELYR,
		EPULSZ,
		Q275.KODENEV AS	FUTESMOD,
		Q276.KODENEV AS	LEGTELTIP,
		Q328.KODENEV AS	LEGTHELY,
		EPULATAD,
		Q277.KODENEV AS	FUTOTIP,
		Q329.KODENEV AS	UZEMELT,
		Q278.KODENEV AS	KARBANTAR,
		EPULHOSZ,
		LAKTERF,
		LEPCSOTERF,
		KOZOSTERF,
		KOZULTERF,
		TERF_ARAM,
		Q272.KODENEV AS	HOLEPCSO,
		EPUL_ARAM,
		CIRK_ARAM,
		Q281.KODENEV AS	FUTBESZAB,
		Q282.KODENEV AS	CIRKUL,
		CASE ATKOTES
			WHEN 'y' THEN 'van'
			WHEN 'n' THEN 'nincs'
		END	AS ATKOTES,
		Q283.KODENEV AS	HMVRENDS,
		NYOMKUL,
		Q284.KODENEV AS	CIRK_MOD,
		Q330.KODENEV AS	FOELZ,
		Q288.KODENEV AS	FELOSZT,
		Q327.KODENEV AS	UTEM
	FROM
		Q327 RIGHT JOIN
			(Q288 RIGHT	JOIN
				(Q330 RIGHT	JOIN
					(Q284 RIGHT	JOIN
						(Q283 RIGHT	JOIN
							(Q282 RIGHT	JOIN
								(Q281 RIGHT	JOIN
									(Q272 RIGHT	JOIN
										(Q278 RIGHT	JOIN
											(Q329 RIGHT	JOIN
												(Q277 RIGHT	JOIN
													(Q328 RIGHT	JOIN
														(Q276 RIGHT	JOIN
															(Q275 RIGHT	JOIN
																(Q274 RIGHT	JOIN
																	(Q289 RIGHT	JOIN
																		(OBJEKTUM INNER	JOIN EPULET	ON EPULET.ID = OBJEKTUM.ID)
																	ON Q289.KODERT = VAROS)
																ON Q274.KODERT = EPULTIP)
															ON Q275.KODERT = FUTESMOD)
														ON Q276.KODERT = LEGTELTIP)
													ON Q328.KODERT = LEGTHELY)
												ON Q277.KODERT = FUTOTIP)
											ON Q329.KODERT = UZEMELT)
										ON Q278.KODERT = KARBANTAR)
									ON Q272.KODERT = HOLEPCSO)
								ON Q281.KODERT = FUTBESZAB)
							ON Q282.KODERT = CIRKUL)
						ON Q283.KODERT = HMVRENDS)
					ON Q284.KODERT = CIRK_MOD)
				ON Q330.KODERT = FOELZ)
			ON Q288.KODERT = FELOSZT)
		ON Q327.KODERT = UTEM
	WHERE
		OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)		AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))
		AND	((@329 IS NULL)	OR (@329 IS	NOT	NULL AND UZEMELT = @329))
		AND	((@278 IS NULL)	OR (@278 IS	NOT	NULL AND KARBANTAR = @278))
		AND	((@277 IS NULL)	OR (@277 IS	NOT	NULL AND FUTOTIP = @277))
		AND	((@281 IS NULL)	OR (@281 IS	NOT	NULL AND FUTBESZAB = @281))
		AND	((@274 IS NULL)	OR (@274 IS	NOT	NULL AND EPULTIP = @274))
	END
/*ELSE IF @pOBJTIP = '02'
	BEGIN
	SELECT
		*
	FROM
		OBJEKTUM INNER JOIN	LAKAS ON LAKAS.ID =	OBJEKTUM.ID
	WHERE
		OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)
		AND	OBJTIP = @pOBJTIP
	END
ELSE*/ IF @pOBJTIP = '03'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TELEPHSZ,
			Q289.KODENEV AS	VAROS,
			UTCA,
			HSZ,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			RTRIM(KEZOSZT) AS KEZOSZT,
			MKHOM,
			HOTELJ,
			GAZCSUCS,
			Q285.KODENEV AS	HOHOR_KO,
			Q272.KODENEV AS	HOLEP,
			VILLCSUCSNY,
			VILLCSUCST,
			TERFARAM,
			CIRKTERFARAM,
			NYOMTARTTIP,
			HMVHOMERS,
			FUT_LAKAS,
			HMV_LAKAS,
			FUT_KOZULET,
			HMV_KOZULET,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(Q285 RIGHT	JOIN
					(Q289 RIGHT	JOIN
						(Q272 RIGHT	JOIN
							(OBJEKTUM INNER	JOIN FUTOMU	ON FUTOMU.ID = OBJEKTUM.ID)
						ON Q272.KODERT = HOLEP)
					ON Q289.KODERT = VAROS)
				ON Q285.KODERT=HOHOR_KO)
			ON Q279.KODERT=	NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

			AND	((@HOTELJTOL IS	NULL OR	@HOTELJIG IS NULL) OR (@HOTELJTOL IS NOT NULL AND @HOTELJIG	IS NOT NULL	AND	HOTELJ BETWEEN @HOTELJTOL AND @HOTELJIG))
			AND	((@NEVLTELJTOL IS NULL OR @NEVLTELJIG IS NULL) OR (@NEVLTELJTOL	IS NOT NULL	AND	@NEVLTELJIG	IS NOT NULL	AND	NEVLTELJ BETWEEN @NEVLTELJTOL AND @NEVLTELJIG))
			AND	((@GAZCSUCSTOL IS NULL OR @GAZCSUCSIG IS NULL) OR (@GAZCSUCSTOL	IS NOT NULL	AND	@GAZCSUCSIG	IS NOT NULL	AND	GAZCSUCS BETWEEN @GAZCSUCSTOL AND @GAZCSUCSIG))
			AND	((@VILLCSUCSNYTOL IS NULL OR @VILLCSUCSNYIG	IS NULL) OR	(@VILLCSUCSNYTOL IS	NOT	NULL AND @VILLCSUCSNYIG	IS NOT NULL	AND	VILLCSUCSNY	BETWEEN	@VILLCSUCSNYTOL	AND	@VILLCSUCSNYIG))
			AND	((@VILLCSUCSTTOL IS	NULL OR	@VILLCSUCSTIG IS NULL) OR (@VILLCSUCSTTOL IS NOT NULL AND @VILLCSUCSTIG	IS NOT NULL	AND	VILLCSUCST BETWEEN @VILLCSUCSTTOL AND @VILLCSUCSTIG))
			AND	((@TERFARAMTOL IS NULL OR @TERFARAMIG IS NULL) OR (@TERFARAMTOL	IS NOT NULL	AND	@TERFARAMIG	IS NOT NULL	AND	TERFARAM BETWEEN @TERFARAMTOL AND @TERFARAMIG))
		END
		ELSE IF	@pOBJTIP = '04'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			GYARTM,
			Q312.KODENEV AS	GYARTO,
			UZEMIDO,
			ELHELYEZ,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			OBJEKTUM.KATEG,
			Q285.KODENEV AS	HOHOR_KO,
			TERFARAM,
			Q318.KODENEV AS	SZABMOD,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(Q285 RIGHT	JOIN
					(Q318 RIGHT	JOIN
						(Q312 RIGHT	JOIN
							(OBJEKTUM INNER	JOIN KAZAN ON KAZAN.ID = OBJEKTUM.ID)
						ON Q312.KODERT=GYARTO)
					ON Q318.KODERT=SZABMOD)
				ON Q285.KODERT=HOHOR_KO)
			ON Q279.KODERT=	NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '05'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			GYARTM,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			BEVTELJ,
			Q318.KODENEV AS	SZABMOD,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(Q318 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN KAZANEGO ON KAZANEGO.ID = OBJEKTUM.ID)
				ON Q318.KODERT = SZABMOD)
			ON Q279.KODERT=	NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '06'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			FORDSZ,
			EMEL_MAG,
			Q285.KODENEV AS	SZAL_KOZ,
			SZAL_MENNY,
			Q319.KODENEV AS	SZIVFOK,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q319 RIGHT JOIN
				(Q285 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN SZIVATTYU ON SZIVATTYU.ID = OBJEKTUM.ID)
				ON Q285.KODERT = SZAL_KOZ)
			ON Q319.KODERT = SZIVFOK
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '07'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			ELHELYEZ,
			NEVLTELJ,
			Q279_1.KODENEV AS NEVLTELJME,
			ELLENALL,
			LEMSZAM,
			MERET,
			Q279_2.KODENEV AS MERETME,
			FUTOFEL,			DB,
			Q285_1.KODENEV AS HOHOR_KO,
			HOSSZ_NAGY,
			HOSSZ_KICS,			FELUGY,
			Q285_2.KODENEV AS FU_KOZ,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q285 Q285_2	RIGHT JOIN
				(Q285 Q285_1 RIGHT JOIN
					(Q279 Q279_2 RIGHT JOIN
						(Q279 Q279_1 RIGHT JOIN
							(OBJEKTUM INNER	JOIN HOCSERELO ON HOCSERELO.ID = OBJEKTUM.ID)
						ON Q279_1.KODERT = NEVLTELJME)
					ON Q279_2.KODERT = MERETME)
				ON Q285_1.KODERT = HOHOR_KO)
			ON Q285_2.KODERT = FU_KOZ
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '08'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			FAGYVED,
			FORDSZ,
			LEGSZAL,
			Q285.KODENEV AS	FU_KOZ,
			ARAMFELV,
			FESZULTS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q285 RIGHT JOIN
				(OBJEKTUM INNER	JOIN VENTILLATOR ON	VENTILLATOR.ID = OBJEKTUM.ID)
			ON Q285.KODERT = FU_KOZ
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '09'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			Q313.KODENEV AS	VESZO,
			FELEP,
			Q320.KODENEV AS	BOYTIP,
			FUTOFEL,
			TERFOGAT,
			Q318.KODENEV AS	SZABMOD,
			Q285.KODENEV AS	FU_KOZ,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q285 RIGHT JOIN
				(Q318 RIGHT	JOIN
					(Q320 RIGHT	JOIN
						(Q313 RIGHT	JOIN
							(OBJEKTUM INNER	JOIN BOYLER	ON BOYLER.ID = OBJEKTUM.ID)
						ON Q313.KODERT = BOYLER.VESZO)
					ON Q320.KODERT = BOYTIP)
				ON Q318.KODERT = SZABMOD)
			ON Q285.KODERT = FU_KOZ
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '10'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			Q326.KODENEV AS	FELEP,
			TERFOGAT,
			KAPCSOLAS,
			Q321.KODENEV AS	TOLTESMOD,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q321 RIGHT JOIN
				(Q326 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN MELEGVIZ_TAROLO ON	MELEGVIZ_TAROLO.ID = OBJEKTUM.ID)
				ON Q326.KODERT = FELEP)
			ON Q321.KODERT = TOLTESMOD
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '11'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			Q326.KODENEV AS	FELEP,
			LEVNYOM,
			VIZNYOM,
			TERFOGAT,
			FUTOTT,
			SZABALYOZAS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q326 RIGHT JOIN
				(OBJEKTUM INNER	JOIN TARTALY ON	TARTALY.ID = OBJEKTUM.ID)
			ON Q326.KODERT = FELEP
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '12'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			Q322.KODENEV AS	SZURTIP,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q322 RIGHT JOIN
				(OBJEKTUM INNER	JOIN SZUROK	ON SZUROK.ID = OBJEKTUM.ID)
			ON Q322.KODERT = SZURTIP
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '13'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			Q318.KODENEV AS	SZABMOD,
			OSZLSZAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q318 RIGHT JOIN
				(Q279 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN VIZLAGYITO	ON VIZLAGYITO.ID = OBJEKTUM.ID)
				ON Q279.KODERT = NEVLTELJME)
			ON Q318.KODERT = SZABMOD
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '14'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			FORDSZ,
			Q285.KODENEV AS	SZAL_KOZ,
			SZAL_MENNY,
			VEGNYOM,
			ARAMFELV,
			FESZULTS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q285 RIGHT JOIN
				(Q279 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN KOMPRESSZOR ON	KOMPRESSZOR.ID = OBJEKTUM.ID)
				ON Q279.KODERT = NEVLTELJME)
			ON Q285.KODERT = SZAL_KOZ
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '15'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TELEPHSZ,
			UZEMIDO,
			BEEPCSOVDB,
			ATMERO,
			HOSSZ,
			VIZSZ,
			BECSOV,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	TERMELO_CSO	ON TERMELO_CSO.ID =	OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '16'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			FORDSZ,
			TERHEL,
			ARAMFELV,
			FESZULTS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN DEMAG_EMELOGEP	ON DEMAG_EMELOGEP.ID = OBJEKTUM.ID)
			ON Q279.KODERT = NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '17'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			UZEMIDO,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			PRIM_ARAM,
		Q272.KODENEV AS	HOLEP,
			RTRIM(FOGYMERHELY) AS FOGYMERHELY,
			KISMEGSZAK,
			LEKVILLTELJ,
			PRIMELL,
			FUT_LAKAS,
			HMV_LAKAS,
			FUT_KOZULET,
			SZEKU_TOM,
			NYOMAS_K,
			HOMER_SZ,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q272 RIGHT JOIN
				(OBJEKTUM INNER	JOIN HOKOZPONT ON HOKOZPONT.ID = OBJEKTUM.ID)
			ON Q272.KODERT = HOLEP
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

			AND	((@PRIM_ARAMTOL	IS NULL	OR @PRIM_ARAMIG	IS NULL) OR	(@PRIM_ARAMTOL IS NOT NULL AND @PRIM_ARAMIG	IS NOT NULL	AND	PRIM_ARAM BETWEEN @PRIM_ARAMTOL	AND	@PRIM_ARAMIG))
			AND	((@SZEKU_TOMTOL	IS NULL	OR @SZEKU_TOMIG	IS NULL) OR	(@SZEKU_TOMTOL IS NOT NULL AND @SZEKU_TOMIG	IS NOT NULL	AND	SZEKU_TOM BETWEEN @SZEKU_TOMTOL	AND	@SZEKU_TOMIG))
		END
		ELSE IF	@pOBJTIP = '18'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			GYARTM,
			UZEMIDO,
			HITIDO,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			ALAIR,
			FKOD,
			IMPULZUS,
			/*Q316.KODENEV AS LEOLVMOD,*/
			FESZULTS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			/*Q316 RIGHT JOIN
				(*/OBJEKTUM	INNER JOIN HOOSSZEGZO ON HOOSSZEGZO.ID = OBJEKTUM.ID/*)
			ON Q316.KODERT = LEOLVMOD*/
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

			AND	((@HOOSZIMPTOL IS NULL OR @HOOSZIMPIG IS NULL) OR (@HOOSZIMPTOL IS NOT NULL AND @HOOSZIMPIG	IS NOT NULL	AND	IMPULZUS BETWEEN @HOOSZIMPTOL AND @HOOSZIMPIG))

		END

		ELSE IF	@pOBJTIP = '19'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			GYARTM,
			UZEMIDO,
			HITIDO,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			ALAIR,
			FKOD,
			/*Q316.KODENEV AS LEOLVMOD,*/
			ATMERO,
			IMPULZUS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			/*Q316 RIGHT JOIN
				(*/OBJEKTUM	INNER JOIN VIZORA ON VIZORA.ID = OBJEKTUM.ID/*)
			ON Q316.KODERT = LEOLVMOD*/
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

			AND	((@VIZATMEROTOL	IS NULL	OR @VIZATMEROIG	IS NULL) OR	(@VIZATMEROTOL IS NOT NULL AND @VIZATMEROIG	IS NOT NULL	AND	VIZORA.ATMERO BETWEEN @VIZATMEROTOL	AND	@VIZATMEROIG))
			AND	((@VIZIMPULZUSTOL	IS NULL	OR @VIZIMPULZUSIG	IS NULL) OR	(@VIZIMPULZUSTOL IS NOT NULL AND @VIZIMPULZUSIG	IS NOT NULL	AND	VIZORA.IMPULZUS BETWEEN @VIZIMPULZUSTOL	AND	@VIZIMPULZUSIG))
		END
		ELSE IF	@pOBJTIP = '20'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			HITIDO,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			VEZHOSSZ,
			BENYHOSSZ,
			Q323.KODENEV AS	KIMENET,
			CSATLMERET,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q323 RIGHT JOIN
				(OBJEKTUM INNER	JOIN ERZEKELO ON ERZEKELO.ID = OBJEKTUM.ID)
			ON Q323.KODERT = KIMENET
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

			AND	((@ERZVEZTOL IS NULL OR @ERZVEZIG IS NULL) OR (@ERZVEZTOL IS NOT NULL AND @ERZVEZIG	IS NOT NULL	AND	ERZEKELO.VEZHOSSZ BETWEEN @ERZVEZTOL AND @ERZVEZIG))
			AND	((@ERZBENYTOL IS NULL OR @ERZBENYIG	IS NULL) OR	(@ERZBENYTOL IS NOT NULL AND @ERZBENYIG	IS NOT NULL	AND	ERZEKELO.BENYHOSSZ BETWEEN @ERZBENYTOL AND @ERZBENYIG))
		END

		ELSE IF	@pOBJTIP = '21'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN FOKAPCSOLO	ON FOKAPCSOLO.ID = OBJEKTUM.ID)
			ON Q279.KODERT = NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '22'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			MEDDTELJ,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	FAZISJAVITO_KONDENZATOR	ON FAZISJAVITO_KONDENZATOR.ID =	OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '23'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	GAZVESZELY_JELZO ON	GAZVESZELY_JELZO.ID	= OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '24'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			GYARTM,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			ARAMFELV,
			FESZULTS,
			VILLFORDSZ,
			TELJT,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN MOTOR ON MOTOR.ID = OBJEKTUM.ID)
			ON Q279.KODERT = NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '25'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	SZINTKAPCSOLO ON SZINTKAPCSOLO.ID =	OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '26'
		BEGIN
	SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	SZABALYOZO_AUTOMATIKA ON SZABALYOZO_AUTOMATIKA.ID =	OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '27'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			MERET,
			Q279.KODENEV AS	MERETME,
			ATMERO,
			Q324.KODENEV AS	MUKMOD,
			KVS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q324 RIGHT JOIN
				(Q279 RIGHT	JOIN
					(OBJEKTUM INNER	JOIN SZABALYOZO_SZELEP ON SZABALYOZO_SZELEP.ID = OBJEKTUM.ID)
				ON Q279.KODERT = MERETME)
			ON Q324.KODERT = MUKMOD
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '28'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			SZELTIP,
			MERET,
			Q279.KODENEV AS	MERETME,
			NYITNYOM,
			ZARNYOM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN BIZTONSAGI_SZELEP ON BIZTONSAGI_SZELEP.ID = OBJEKTUM.ID)
			ON Q279.KODERT = MERETME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '29'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
			UZEMIDO,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			MKHOM,
			KIMARAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN FREKVENCIAVALTO ON	FREKVENCIAVALTO.ID = OBJEKTUM.ID)
			ON Q279.KODERT = NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '30'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			UZEMIDO,
			Q272.KODENEV AS	HOLEP,
			TERFOGAT,
			HOSSZ,
			SZABALYOZAS,
			FUT_LAKAS,
			HMV_LAKAS,
			FUT_KOZULET,
			HMV_KOZULET,
			HOKOZP_SZAM,
			NYOMKUL,
			TOMEGARAM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q272 RIGHT JOIN
				(OBJEKTUM INNER	JOIN ARAMKOR ON	ARAMKOR.ID = OBJEKTUM.ID)
			ON Q272.KODERT = HOLEP
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '31'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	KOLTSEGMEGOSZTO	ON KOLTSEGMEGOSZTO.ID =	OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '32'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			FKOD,
			ATMERO,
			FUR_ATM,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	TARCSA ON TARCSA.ID	= OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '33'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			GYSZAM,
		RTRIM(GYARTM) AS GYARTM,
			NEVLTELJ,
			Q279.KODENEV AS	NEVLTELJME,
			ATMERO,
			RTRIM(BEALL_ERTEK) AS BEALL_ERTEK,
			ARAMFELV,
			FESZULTS,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q279 RIGHT JOIN
				(OBJEKTUM INNER	JOIN HAJTOMU ON	HAJTOMU.ID = OBJEKTUM.ID)
			ON Q279.KODERT = NEVLTELJME
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '34'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			RTRIM(GYARTM) AS GYARTM,
			ARAMFELV,
			FESZULTS,
			VEZHOSSZ,
			BENYHOSSZ,
			NYOMATEK,
			ERZEKENY,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	LANGOR ON LANGOR.ID	= OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '35'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			UZEMIDO,
			Q289.KODENEV AS	VAROS,
			UTCA,
			HSZ,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			Q289 RIGHT JOIN
				(OBJEKTUM INNER	JOIN TERMALKUT ON TERMALKUT.ID = OBJEKTUM.ID)
			ON Q289.KODERT = VAROS
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END
		ELSE IF	@pOBJTIP = '36'
		BEGIN
		SELECT
			OBJEKTUM.ID,
			RTRIM(MEGNEV) AS MEGNEV,
			TIPUS,
			TELEPHSZ,
			RTRIM(GYARTM) AS GYARTM,
			RTRIM(ELHELYEZ)	AS ELHELYEZ,
			ATMERO,
			RTRIM(BEALL_ERTEK) AS BEALL_ERTEK,
			RTRIM(MEGJ)	AS MEGJ
		FROM
			OBJEKTUM INNER JOIN	SZERELVENY ON SZERELVENY.ID	= OBJEKTUM.ID
		WHERE
			OBJEKTUM.ID	= coalesce(@pID,OBJEKTUM.ID)			AND (OBJEKTUM.MEGNEV like coalesce(@pMEGNEV, OBJEKTUM.MEGNEV))

		END

RETURN 0